import fs from 'node:fs'

import json from '@rollup/plugin-json'
import { nodeResolve } from '@rollup/plugin-node-resolve'
import typescript from '@rollup/plugin-typescript'
import copy from 'rollup-plugin-copy'

import PackageJSON from './package.json' with { type: 'json' }

export default {
  input: './index.ts',
  output: {
    file: './build/bundle.js',
    format: 'esm',
    banner: generateHeader()
  },
  external: [/^node:\w+/gi, ...Object.keys(PackageJSON.dependencies), ...Object.keys(PackageJSON.devDependencies)],
  plugins: [
    json(),
    nodeResolve(),
    typescript({ tsconfig: './tsconfig.json', sourceMap: false }),
    copy({
      targets: [
        { src: 'resources/fonts', dest: 'build/resources/fonts' },
        { src: 'resources/*', dest: 'build/resources/' },
        { src: 'config_example.yaml', dest: 'build/' },
        { src: 'LICENSE', dest: 'build/' },
        { src: 'package*', dest: 'build/' },
        { src: '*.md', dest: 'build/' },
        { src: 'docs', dest: 'build/' },
        { src: 'start.sh', dest: 'build/' },
        { src: 'setup-and-start.bat', dest: 'build/' }
      ]
    })
  ]
}

function generateHeader() {
  let message = ''
  message += '// This file is auto-generated by Rollup'
  message += '\n// Do not edit manually.'

  message += '\n\n'
  message += `\n// Author: ${PackageJSON.author}`
  message += `\n// Repository: ${PackageJSON.repository.url}`
  message += `\n// Version: ${PackageJSON.version}`

  message += '\n\n'
  message += '\n// LICENSE:'
  message += fs
    .readFileSync('LICENSE', 'utf8')
    .split('\n')
    .map((line) => `\n// ${line}`)
    .join('')

  message += '\n\n'
  message += '\n// ===== Start Global Options ====='
  message += `\n${generateGlobalOptions()}`
  message += '\n// ===== End Global Options ===='
  message += '\n'.repeat(3)

  return message
}

function generateGlobalOptions() {
  let code = ''
  code += '\nconst RollupUsed = true;'
  return code
}
