import type { ChatEvent } from '../../../common/application-event'
import { ChannelType, Color } from '../../../common/application-event'
import { SpontaneousEventsNames } from '../../../core/spontanmous-events-configurations'
import Duration from '../../../utility/duration'
import { Timeout } from '../../../utility/timeout'
import { type EventContext, shuffleArrayInPlace, SpontaneousEventHandler } from '../common'

export class Unscramble extends SpontaneousEventHandler {
  override enabled(): boolean {
    return this.application.core.spontaneousEventsConfigurations
      .getEnabledEvents()
      .includes(SpontaneousEventsNames.Unscramble)
  }

  override async startEvent(): Promise<void> {
    const context: EventContext = {
      application: this.application,
      eventHelper: this.eventHelper,
      logger: this.logger,
      broadcastMessage: (message, color) => this.broadcastMessage(message, color)
    }

    const result = await startUnscramble(context, Duration.seconds(30))
    await context.broadcastMessage(result.message, result.color)
  }
}

const ScrambleWords = [
  // generic
  'Apple',
  'Banana',
  'Grape',
  'Lemon',
  'Cherry',
  'Peach',
  'Mango',
  'Kiwi',
  'Plum',
  'Table',
  'Chair',
  'Couch',
  'Desk',
  'Shelf',
  'Blanket',
  'Curtain',
  'House',
  'Garden',
  'Porch',
  'Fence',
  'Roof',
  'Window',
  'Door',
  'Floor',
  'Stairs',
  'Attic',
  'Water',
  'Coffee',
  'Juice',
  'Soda',
  'Milk',
  'Bread',
  'Cheese',
  'Butter',
  'Egg',
  'Dog',
  'Cat',
  'Bird',
  'Fish',
  'Horse',
  'Rabbit',
  'Mouse',
  'Snake',
  'Frog',
  'Sun',
  'Star',
  'Cloud',
  'Rain',
  'Snow',
  'Wind',
  'Storm',
  'Thunder',
  'Lightning',
  'Red',
  'Blue',
  'Green',
  'Yellow',
  'Purple',
  'Pink',
  'Brown',
  'White',
  'Happy',
  'Sad',
  'Scared',
  'Brave',
  'Tired',
  'Sleepy',
  'Hungry',
  'Thirsty',
  'Excited',
  'Run',
  'Walk',
  'Jump',
  'Swim',
  'Sing',
  'Read',
  'Write',
  'Draw',
  'Car',
  'Bike',
  'Bus',
  'Train',
  'Plane',
  'Boat',
  'Ship',
  'Truck',
  'Scooter',
  'School',
  'Teacher',
  'Student',
  'Pencil',
  'Paper',
  'Eraser',
  'Ruler',
  'Map',
  'Pillow',
  'Tea',
  'Moon',
  'Black',
  'Dance',
  'Book',
  'Lamp',
  'Turtle',
  'Climb',
  'Taxi',
  'Honey',
  'Goblin Shark',
  'Bull Shark',
  'Blue Marlin',
  'Fox',
  'Wolf',
  'Deer',
  'Otter',
  'Seal',
  'Whale',
  'Falcon',
  'Eagle',
  'Hawk',
  'Burger',
  'Pizza',
  'Pasta',
  'Cookie',
  'Donut',
  'Muffin',
  'Sandwich',
  'Bottle',
  'Basket',
  'Mirror',
  'Kitchen',
  'Bedroom',
  'Hallway',
  'Garage',
  'Balcony',
  'Basement',
  'Closet',
  'Bathroom',
  'Village',
  'Castle',
  'Fog',
  'Mist',
  'Rainbow',
  'Tornado',
  'Meteor',
  'Comet',
  'Planet',
  'Galaxy',
  'Rocket',
  'Satellite',

  // hypixel generic
  'SkyBlock',
  'Bed Wars',
  'Duels',
  'SkyWars',
  'Murder Mystery',
  'Blitz SG',
  'Paintball',
  'TNT Games',
  'Arcade',
  'Mega Walls',
  'Build Battle',
  'Pit',
  'Classic',
  'Arena',
  'Lobby',
  'Hub',
  'Quest',
  'Daily',
  'Reward',
  'Token',
  'Crown',
  'Relic',
  'Dragon',
  'Phoenix',
  'Wither',
  'Ender',
  'Slime',
  'Zombie',
  'Skeleton',
  'Creeper',
  'Minion',
  'Pet',
  'Armor',
  'Sword',
  'Bow',
  'Axe',
  'Pickaxe',
  'Shovel',
  'Hoe',
  'Shield',
  'Potion',
  'Brew',
  'Enchant',
  'Grindstone',
  'Anvil',
  'Forge',
  'Talisman',
  'Rune',
  'Scroll',
  'Gem',
  'Island',
  'Farm',
  'Mine',
  'Quarry',
  'Nether',
  'Overworld',
  'End',
  'Portal',
  'Warp',
  'Spawn',
  'Queue',
  'Match',
  'Round',
  'Team',
  'Solo',
  'Duo',
  'Trio',
  'Squad',
  'Clan',
  'Rank',
  'Level',
  'XP',
  'Prestige',
  'Boost',
  'Upgrade',
  'Shop',
  'Market',
  'Auction',
  'Trade',
  'Vote',
  'Vote Crate',
  'Crate',
  'Loot',
  'Chest',
  'Key',
  'Mystery Box',
  'Surprise',
  'Event',
  'Festival',
  'Holiday',
  'Halloween',
  'Christmas',
  'Easter',
  'Summer',
  'Winter',
  'Spring',
  'Autumn',
  'Fireworks',

  // minecraft
  'Block',
  'Arrow',
  'Helmet',
  'Chestplate',
  'Boots',
  'Furnace',
  'Crafting Table',
  'Enchanting Table',
  'Brewing Stand',
  'Redstone',
  'Piston',
  'Lever',
  'Button',
  'Pressure Plate',
  'Torch',
  'Lantern',
  'Glowstone',
  'Obsidian',
  'Emerald',
  'Gold',
  'Iron',
  'Coal',
  'Charcoal',
  'Lapis',
  'Quartz',
  'Netherite',
  'Slimeball',
  'Feather',
  'Leather',
  'Wool',
  'Compass',
  'Bucket',
  'Lava',
  'Sand',
  'Gravel',
  'Dirt',
  'Grass',
  'Stone',
  'Cobblestone',
  'Mossy',
  'Basalt',
  'Soulsoil',
  'End Stone',
  'Prismarine',
  'Sea Lantern',
  'Kelp',
  'Coral',
  'Sponge',
  'Ice',
  'Cactus',
  'Vines',
  'Lilypad',
  'Oak',
  'Birch',
  'Spruce',
  'Jungle',
  'Acacia',
  'Dark Oak',
  'Mangrove',
  'Bamboo',
  'Chorus',
  'Mushroom',
  'Spider',
  'Enderman',
  'Witch',
  'Ghast',
  'Blaze',
  'Shulker',
  'Villager',
  'Pig',
  'Cow',
  'Sheep',
  'Chicken',
  'Dolphin',
  'Crafter',
  'Mace',
  'Heavy Core',
  'Wind Charge',
  'Breeze Rod',
  'Trial Key',
  'Ominous Trial Key',
  'Ominous Bottle',
  'Trial Spawner',
  'Ominous Trial Spawner',
  'Vault',
  'Ominous Vault',
  'Breeze',
  'Bogged',
  'Golden Apple',
  'Enchanted Golden Apple',
  'Ender Pearl',
  'Eye of Ender',
  'Totem of Undying',
  'Elytra',
  'Trident',
  'Crossbow',
  'Spyglass',
  'Brush',
  'Turtle Helmet',
  'Recovery Compass',
  'Goat Horn',
  'Name Tag',
  'Saddle',
  'Lead',
  'Book and Quill',
  'Dragon Egg',
  'Echo Shard',
  'Chorus Fruit',
  'Chorus Flower',
  'Chorus Plant',
  'Moss Block',
  'Moss Carpet',
  'Packed Ice',
  'Blue Ice',
  'Netherrack',
  'Soul Sand',
  'Bone Block',
  'Hay Bale',
  'Target',
  'Campfire',
  'Soul Campfire',
  'Respawn Anchor',
  'Nether Star',
  'Beacon',
  'Conduit',
  'Heart of the Sea',
  'Prismarine Shard',
  'Prismarine Crystals',
  'Amethyst Shard',
  'Calcite',
  'Tuff',
  'Dripstone Block',
  'Pointed Dripstone',
  'Deepslate',
  'Reinforced Deepslate',
  'Frogspawn',
  'Tadpole Bucket',
  'Sniffer Egg',
  'Pitcher Plant',
  'Torchflower',
  'Decorated Pot',
  'Armadillo Scute',

  // skyblock
  'Combat',
  'Jerry',
  'Farming',
  'Foraging',
  'Galatea',
  'Kills',
  'Slayer',
  'Sven',
  'Player',
  'Skill',
  'Dungeon',
  'Healer',
  'Berserk',
  'Mage',
  'Archer',
  'Tank',
  'French Bread',
  'Pioneer Pickaxe',
  'Campaign Poster',
  'Moldy Muffin',
  'Creative Mind',
  'Quality Map',
  'Dead Bush Of Love',
  'Wiki Journal',
  "Editor's Pencil",
  'Game Breaker',
  'Game Annihilator',
  'Ancient Elevator',
  'Kloonboat',
  'Space Helmet',
  'Shiny Relic',
  'Piece Of Wizard Portal',
  'Expensive Toy',
  'Golden Collar',
  'Locked Ballot Box',
  'There And Back Again',
  'Dreamspire Torch',
  'Spooky Pie',
  'New Year Cake',
  'Golden Gift',
  'Bingo Card',
  'Kuudra Follower Helmet',
  'Kuudra Follower Chestplate',
  'Kuudra Follower Leggings',
  'Kuudra Follower Boots',
  'Kuudra Relic',
  'Wet Napkin',
  'Kuudra Teeth Plaque',
  'Supreme Timecharm',
  'Chicken N Egg Timecharm',
  'mrahcemiT esrevrorriM',
  'SkyBlock Citizen Timecharm',
  'Living Timecharm',
  'Globulate Timecharm',
  'Vampiric Timecharm',
  'Celestial Timecharm',
  'Colossal Experience Bottle Upgrade',
  'Heat Core',
  'God Potion',
  'Kat Flower',
  'Ultimate Carrot Candy',
  'Superb Carrot Candy',
  'Great Carrot Candy',
  'Private Island',
  'The Barn',
  'Mushroom Desert',
  'The Park',
  'The End',
  'Crimson Isle',
  'Gold Mine',
  'Deep Caverns',
  'Dwarven Mines',
  'Crystal Hollows',
  'Dungeon Hub',
  'Rift Dimension',
  'Backwater Bayou',
  'Aatrox',
  'Adventurer',
  'Alchemist',
  'Alixer',
  'Amelia',
  'Anita',
  'Andrew',
  'Apprentice',
  'Arthur',
  'Auction Master',
  'Auction Agents',
  'Baker',
  'Banker',
  'Bartender',
  'Bazaar',
  'Bazaar Agent',
  'Bea',
  'Biblio',
  'Billy Joe',
  'Blacksmith',
  'Bobby Joe',
  'Builder',
  'Carnival Cowboy',
  'Carnival Fisherman',
  'Carnival Leader',
  'Carnival Pirateman',
  'Carpenter',
  'Chantelle',
  'Christopher',
  'Clerk Seraphine',
  'Coach Jackrabbit',
  'Cole',
  'Curator',
  'Damia',
  'Derpy',
  'Diana',
  'Diaz',
  'Doug',
  'Duke',
  'Dusk',
  'Elizabeth',
  'Erihann',
  'Fann',
  'Farm Merchant',
  'Farmer',
  'Fear Mongerer',
  'Felix',
  'Finnegan',
  'Fishing Merchant',
  'Fisherman Gerald',
  'Foxy',
  'George',
  'Gladiator',
  'Guy',
  'Hootie',
  'Hoppity',
  'Jack',
  'Jacob',
  'Jacobus',
  'Jamie',
  'Jax',
  'Jerry',
  'Jim Bob',
  'Liam',
  'Librarian',
  'Lonely Philosopher',
  'Lucius',
  'Lumber Jack',
  'Lumber Merchant',
  'Mad Redstone Engineer',
  'Maddox the Slayer',
  'Marina',
  'Maths Enjoyer',
  'Mine Merchant',
  'Oringo',
  'Ozanne',
  'Ophelia',
  'Security Sloth',
  'Salesman',
  'Seymour',
  'Tyashoi Alchemist',
  'Wool Weaver',
  'Udium',
  'Romero',
  'Old Shaman Nyko',
  'Sea Walker',
  'Squid',
  'Night Squid',
  'Sea Guardian',
  'Sea Witch',
  'Sea Archer',
  'Rider of the Deep',
  'Catfish',
  'Carrot King',
  'Agarimoo',
  'Sea Leech',
  'Guardian Defender',
  'Deep Sea Protector',
  'Water Hydra',
  'The Loch Emperor',
  'Frog Man',
  'Snapping Turtle',
  'Wiki Tiki',
  'Oasis Rabbit',
  'Oasis Sheep',
  'Water Worm',
  'Poisoned Water Worm',
  'Abyssal Miner',
  'Large Mithril Grubber',
  'Medium Mithril Grubber',
  'Mithril Grubber',
  'Dumpster Diver',
  'Trash Gobbler',
  'Banshee',
  'Bayou Sludge',
  'Alligator',
  'Titanoboa',
  'Scarecrow',
  'Nightmare',
  'Werewolf',
  'Phantom Fisher',
  'Grim Reaper',
  'Frozen Steve',
  'Frosty',
  'Grinch',
  'Yeti',
  'Nutcracker',
  'Reindrake',
  'Nurse Shark',
  'Blue Shark',
  'Tiger Shark',
  'Great White Shark',
  'Magma Slug',
  'Moogma',
  'Lava Leech',
  'Pyroclastic',
  'Lava Flame',
  'Fire Eel',
  'Taurus',
  'Plhlegblast',
  'Thunder',
  'Lord Jawbus',
  'Fried Chicken',
  'Fireproof Witch',
  'Fiery Scuttler',
  'Ragnarok',
  'Flaming Worm',
  'Lava Blaze',
  'Lava Pigman'
]

export async function startUnscramble(
  context: EventContext,
  time: Duration
): Promise<{ message: string; color: Color }> {
  const chosenWord = pickWord()

  const timeout = new Timeout<ChatEvent>(time.toMilliseconds())

  const listener = (event: ChatEvent) => {
    if (event.channelType !== ChannelType.Public) return

    const match = event.message.trim()
    if (match.toLowerCase() === chosenWord.original.toLowerCase()) timeout.resolve(event)
  }

  context.application.on('chat', listener)
  timeout.refresh()
  await context.broadcastMessage(`Unscramble: ${chosenWord.scrambled}`, Color.Good)

  const result = await timeout.wait()
  context.application.off('chat', listener)

  // eslint-disable-next-line unicorn/prefer-ternary
  if (result === undefined) {
    return { message: `The answer is: ${chosenWord.original} :(`, color: Color.Info }
  } else {
    return { message: `Good job ${result.user.displayName()}!`, color: Color.Good }
  }
}

function pickWord(): { original: string; scrambled: string } {
  const wordsToPickFrom = ScrambleWords.map((entry) => entry.trim())
    .filter((entry) => entry.length >= 3)
    .filter((entry) => /^[\w\s]+$/.test(entry))

  const pickedWord = wordsToPickFrom[Math.floor(Math.random() * wordsToPickFrom.length)]
  // eslint-disable-next-line @typescript-eslint/no-misused-spread
  const characters = [...pickedWord]
  const letters = characters.filter((character) => character !== ' ')
  const pickedWordReversed = letters.toReversed().join('')

  for (let tryCount = 0; tryCount < 50; tryCount++) {
    const scrambledLetters = shuffleArrayInPlace([...letters])
    const scrambled = applyLettersToPattern(characters, scrambledLetters)

    if (scrambled !== pickedWord && scrambled.replaceAll(' ', '') !== pickedWordReversed) {
      return { original: pickedWord, scrambled: scrambled }
    }
  }

  return {
    original: pickedWord,
    // eslint-disable-next-line @typescript-eslint/no-misused-spread
    scrambled: applyLettersToPattern(characters, [...pickedWordReversed])
  }
}

function applyLettersToPattern(pattern: string[], letters: string[]): string {
  let letterIndex = 0
  return pattern.map((character) => (character === ' ' ? ' ' : letters[letterIndex++])).join('')
}
