/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const GeneralConfig = t.iface([], {
  "hypixelApiKey": "string",
});

export const StaticDiscordConfig = t.iface([], {
  "key": "string",
  "adminIds": t.array("string"),
});

export const MetricsConfig = t.iface([], {
  "enabled": "boolean",
  "port": "number",
  "prefix": "string",
});

export const ApplicationConfig = t.iface([], {
  "version": "number",
  "general": "GeneralConfig",
  "discord": "StaticDiscordConfig",
  "metrics": "MetricsConfig",
  "plugins": t.array("string"),
});

const exportedTypeSuite: t.ITypeSuite = {
  GeneralConfig,
  StaticDiscordConfig,
  MetricsConfig,
  ApplicationConfig,
};
export default exportedTypeSuite;
