/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const GeneralConfig = t.iface([], {
  "hypixelApiKey": "string",
  "shareMetrics": "boolean",
});

export const StaticDiscordConfig = t.iface([], {
  "key": "string",
  "adminIds": t.array("string"),
});

export const PrometheusConfig = t.iface([], {
  "enabled": "boolean",
  "port": "number",
  "prefix": "string",
});

export const ApplicationConfig = t.iface([], {
  "version": t.lit(2),
  "general": "GeneralConfig",
  "discord": "StaticDiscordConfig",
  "prometheus": "PrometheusConfig",
});

const exportedTypeSuite: t.ITypeSuite = {
  GeneralConfig,
  StaticDiscordConfig,
  PrometheusConfig,
  ApplicationConfig,
};
export default exportedTypeSuite;
